
- name: Ensure Logstash is enabled on boot.
  service:
    name: logstash
    enabled: "{{ logstash_enabled_on_boot }}"

- name: Make logstash dir on /data/logstash
  file:
    state: directory
    path: /data/logstash
    owner: logstash
    group: logstash


- name: Place configs
  copy:
    src: ../files/{{ item }}
    dest: /etc/logstash/{{ item }}
  loop:
    - "logstash.yml.j2"
    - "pipelines.yml"
    - "jvm.options"
  notify: restartLogstash

- name: Place pipelines
  copy:
    src: ../files/{{ item }}
    dest: /etc/logstash/pipeline/{{ item }}
  loop:
    - "accesslog.pipeline"
    - "gwaccesslog.pipeline"
    - "inbound.pipeline"
    - "transaction.pipeline"
  notify: restartLogstash

- name: Place cert
  copy:
    src: "{{ca_cert_path}}"
    dest: /etc/pki/ca-trust/extracted/pem/elasticsearch-ca.pem
    owner: root
    group: root
    mode: 0644
  notify: restartLogstash

- name: Template in the output pipeline
  template:
    src: ../templates/{{item}}.j2
    dest: /etc/logstash/pipeline/{{item}}
  notify: restartLogstash
  loop:
  - "jvm.options.j2"
  - "logstash.yml.j2"
  - "pipelines.yml.j2"
  - "output.pipeline.j2"


  # /etc/elasticsearch/certs/
  # xpack.security.transport.ssl.keystore.path: certs/elastic-certificates.p12
  #xpack.security.transport.ssl.truststore.path: certs/elastic-certificates.p12

